routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

/*
 * Authentication routing table
 */
Auth::routes();

/*
 * Essential routing table
 */
Route::get('/', 'HomeController@index');
Route::resource('profile', 'ProfileController', ['only' => ['index', 'update']]);

/*
 * EventController routing table
 */
Route::resource('event', 'EventController');
Route::resource('share', 'ShareController', ['only' => ['show']]);
Route::resource('test', 'PhotoController');

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

/**
 * Class Event
 * @package App
 */
class Event extends Model
{
    use Notifiable;

    /**
     * Cast key type to string
     *
     * @var string
     */
    protected $keyType = 'string';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'name', 'description', 'start_date', 'end_date', 'start_time', 'end_time',
        'location', 'latitude', 'longitude', 'img_url', 'cost', 'contracts_id', 'users_id'
    ];


    /**
     * Making a relationship between Event Model
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function contract(){
    	return $this->hasOne('App\Contract', 'id', 'contracts_id');
    }

    public function categories(){
        return $this->belongsToMany('App\Categories');
    }

}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Categories;
use Illuminate\Http\Request;

use Auth;
use App\Event;
use App\Contract;
use App\Http\Requests;
use Illuminate\Support\Facades\DB;

class EventController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * The attributes that are custom validator message.
     *
     * @var array
     */
    private $validatorMessages = [

    ];

    /**
     * Display a adding list of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $events = Event::all()->sortBy('created_at');
        return view('event.manage', ['events' => $events]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('event.fill');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        $this->validate($request, [
//            'name' => 'required',
//            'description' => 'required',
//            'start_date' => 'required',
//            'end_date' => 'required',
//            'start_time' => 'required',
//            'end_time' => 'required',
//            'location' => 'required',
//            'price' => 'numeric',
//            'phone_number' => 'required|numeric',
//        ], $this->validatorMessages);

        //Contracts ID and Users ID
        $users_id = Auth::user()->id;
        $contract_id = str_random(5);
        Contract::create([
            'id' => $contract_id,
            'name' => $request->agency,
            'email' => $request->email,
            'phone_number' => $request->phone_number,
            'facebook_url' => $request->facebook_url,
            'twitter_url' => $request->twitter_url,
            'website' => $request->website
        ]);

        // Add a image to storage
        if ($request->hasFile('image')) {
            $filename = str_random(30). '.' . $request->file('image')->getClientOriginalExtension();
            $request->file('image')->storeAs('public/', $filename);
            $path = asset('storage/'.$filename);
        } else {
            $path = null;
        }

        if ($request->cost == null) {
            $cost = 0;
        } else {
            $cost = $request->cost;
        }
        // Add a event record
        $events_id = str_random(60);
        Event::create([
            'id' => $events_id,
            'name' => $request->activity_name,
            'description' => $request->description,
            'start_date' => $request->start_date,
            'end_date' => $request->end_date,
            'start_time' => $request->start_time,
            'end_time' => $request->end_time,
            'location' => $request->location,
            'latitude' => $request->latitude,
            'longitude' => $request->longitude,
            'cost' => $cost,
            'img_url' => $path,
            'contracts_id' => $contract_id,
            'users_id' => $users_id,
        ]);

        // Add categories to events relation
        foreach($request->categories as $selected) {
            DB::table('events_categories')->insert([
                'events_id' => $events_id,
                'categories_id' => $selected,
            ]);
        }

        return redirect()->route('event.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $detail = Event::where('id', $id)->with('contract')->first();
        return view('event.detail', ['detail' => $detail]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $detail = Event::where('id', $id)->with('contract')->first();
        return view('event.edit', ['detail' => $detail]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //Contracts ID and Users ID
        $contract_id = DB::table('events')->select('contracts_id')->where('id', $id)->first();
        Contract::where('id', $contract_id->contracts_id)->update([
            'name' => $request->agency,
            'email' => $request->email,
            'phone_number' => $request->phone_number,
            'facebook_url' => $request->facebook_url,
            'twitter_url' => $request->twitter_url,
            'website' => $request->website
        ]);

        // Add a image to storage
        if ($request->hasFile('image')) {
            $filename = str_random(30). '.' . $request->file('image')->getClientOriginalExtension();
            $request->file('image')->storeAs('public/', $filename);
            $path = asset('storage/'.$filename);
        } else {
            $path = null;
        }

        if ($request->cost == null) {
            $cost = 0;
        } else {
            $cost = $request->cost;
        }

        // Add a event record
        Event::where('id', $id)->update([
            'id' => $id,
            'name' => $request->activity_name,
            'description' => $request->description,
            'start_date' => $request->start_date,
            'end_date' => $request->end_date,
            'start_time' => $request->start_time,
            'end_time' => $request->end_time,
            'location' => $request->location,
            'latitude' => $request->latitude,
            'longitude' => $request->longitude,
            'cost' => $request->cost,
            'img_url' => $path,
        ]);

        // Add categories to events relation
        DB::table('events_categories')->where('events_id', $id)->delete();
        foreach($request->categories as $selected) {
            DB::table('events_categories')->where('events_id', $id)->update([
                'categories_id' => $selected,
            ]);
        }

        return redirect()->route('event.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $contract_id = DB::table('events')->select('contracts_id')->where('id', $id)->first();
        DB::table('contracts')->where('id', $contract_id->contracts_id)->delete();
        DB::table('events')->where('id', $id)->delete();
        return redirect()->route('event.index');
    }
}

resources/views/event/detail.blade.php
@extends('layouts.app')
@section('blade_name')
      <h1>ข้อมูลกิจกรรมในฐานข้อมูล
            <small>Event Description</small>
      </h1>
@endsection
@section('content')
      <div class="box box-success">
            <div class="box-header">
                  <h3 class="box-title">รายละเอียดกิจกรรม</h3>
            </div>
            <div class="box-body">
                  <strong><i class="fa fa-book margin-r-5"></i> ชื่อกิจกรรม</strong>
                  <p class="text-muted">
                        {{ $detail->name }}
                  </p>
                  <hr>
                  <strong><i class="fa fa-pencil margin-r-5"></i> รายละเอียดของกิจกรรม</strong>
                  <p class="text-muted">
                        {{ $detail->description }}
                  </p>
                  <hr>
                  <strong><i class="fa fa-clock-o margin-r-5"></i> วันที่จัดกิจกรรม</strong>
                  <p class="text-muted">
                        {{ $detail->start_date }} ถึง {{ $detail->end_date }}
                  </p>
                  <hr>
                  @if ($detail->cost != 0)
                        <strong><i class="fa fa-dollar margin-r-5"></i> ราคาบัตร</strong>
                        <p class="text-muted">
                              {{ $detail->cost }} บาท
                        </p>
                        <hr>
                  @else
                        <strong><i class="fa fa-dollar margin-r-5"></i> ราคาบัตร</strong>
                        <p class="text-muted">
                              ฟรี
                        </p>
                        <hr>
                  @endif
                  <strong><i class="fa fa-map-marker margin-r-5"></i> สถานที่จัดกิจกรรม</strong>
                  <p class="text-muted">
                        {{ $detail->location }}
                  </p>
                  <hr>
                  <strong><i class="fa fa-tags margin-r-5"></i> Tag</strong>
                  <p>
                        <span class="label label-danger">UI Design</span>
                        <span class="label label-success">Coding</span>
                        <span class="label label-info">Javascript</span>
                        <span class="label label-warning">PHP</span>
                        <span class="label label-primary">Node.js</span>
                  </p>
                  <hr>
            </div>
      </div>

      <div class="box box-success">
            <div class="box-header">
                  <h3 class="box-title">รายละเอียดผู้จัดกิจกรรม</h3>
            </div>
            <div class="box-body">
                  <strong><i class="fa fa-users margin-r-5"></i>กลุ่มผู้จัดกิจกรรม</strong>
                  <p class="text-muted">
                        {{ $detail->contract->name }}
                  </p>
                  <hr>
                  <strong><i class="fa fa-phone margin-r-5"></i>เบอร์โทรศัพท์</strong>
                  <p class="text-muted">
                        {{ $detail->contract->phone_number }}
                  </p>
                  <hr>
                  <strong><i class="fa fa-envelope margin-r-5"></i>E-mail address</strong>
                  <p class="text-muted">
                        {{ $detail->contract->email }}
                  </p>
                  <hr>
                  @if ($detail->facebook != null)
                        <strong><i class="fa fa-facebook-official margin-r-5"></i>Facebook</strong>
                        <a class="text-muted" href="{{ $detail->facebook_url }}">
                              {{ $detail->contract->facebook_url }}
                        </a>
                        <hr>
                  @endif
                  @if ($detail->line != null)
                        <strong><i class="fa fa-external-link margin-r-5"></i>Line ID</strong>
                        <p class="text-muted">
                              {{ $detail->contract->line_id }}
                        </p>
                        <hr>
                  @endif
                  @if ($detail->twitter != null)
                        <strong><i class="fa fa-twitter margin-r-5"></i>Twitter</strong>
                        <a class="text-muted" href="{{ $detail->twitter_url }}">
                              {{ $detail->contract->twitter_url }}
                        </a>
                        <hr>
                  @endif
            </div>
      </div>
      <a role="button" class="btn btn-success btn-block" href="{{ url('/event.manage') }}">กลับสู่หน้าจัดการกิจกรรม</a>
@endsection

resources/views/event/manage.blade.php
@extends('layouts.app')
@section('blade_name')
    <h1>กิจกรรมที่ดูแลทั้งหมด
        <small>Event Management</small>
    </h1>
@endsection
@section('content')
    <div class="box box-primary">
        <div class="box-body">
            @if($events->isEmpty())
                    <h3 class="text-center">ขออภัย ไม่มีกิจกรรมในระบบ</h3>
                    <br>
                    <a role="button" class="btn btn-success btn-block" href="{{ route('event.create') }}">เพิ่มกิจกรรม</a>
            @else
                <div class="callout callout-danger">
                    <h4>คำเตือน!</h4>
                    <ul>
                        <li>ระบบจะแสดงเฉพาะกิจกรรมที่คุณกำกับดูแลอยู่เท่านั้น</li>
                        <li>เมื่อทำการแก้ไขหรือลบกิจกรรมแล้ว จะไม่สามารถย้อนกลับได้</li>
                    </ul>
                </div>
                <hr>
                @foreach($events as $event)
                    <div class="row">
                        <div class="col-md-9 col-xs-12 lead">
                            {{ $event->name }}
                        </div>
                        <div class="col-md-3 col-xs-12">
                            <div class="btn-group btn-group-justified">
                                <a role="button" class="btn btn-block btn-success" href="{{ route('event.show', $event->id) }}">ดูข้อมูล</a>
                                <a role="button" class="btn btn-info"
                                   href="{{ route('event.edit', $event->id) }}">แก้ไข</a>
                                <a role="button" class="btn btn-danger" data-toggle="modal" data-target="#{{ $event->id }}">ลบ</a>
                            </div>
                        </div>
                    </div>

                    <!-- Modal -->
                    <div class="modal fade alert-modal" id="{{ $event->id }}" tabindex="-1" role="dialog"
                         aria-labelledby="myModalLabel">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                                aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="myModalLabel">ต้องการลบกิจกรรม "{{ $event->name }}"</h4>
                                </div>
                                <div class="modal-body">
                                    หากลบแล้วจะไม่สามารถกู้คืนข้อมูลได้อีก ยืนยัน?
                                </div>
                                <div class="modal-footer">
                                    <form class="form-horizontal" role="form" method="POST" action="{{ route('event.destroy', $event->id) }}">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <button type="button" class="btn btn-default" data-dismiss="modal">ยกเลิก</button>
                                        <button type="submit" class="btn btn-primary">ยืนยัน</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            @endif
        </div>
    </div>
@endsection
@section('js')
    <script type="text/javascript">
        $('.alert_modal').modal({
            keyboard: false
        })
    </script>
@endsection

resources/views/event/share.blade.php
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>KMITL Event</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('css/font-awesome.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset('css/ionicons.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('css/share-style.css') }}">
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&key=AIzaSyB_vaUc8yJZXXtsg1S0hcWkh4Rl7obcLzE"></script>

    <link rel="stylesheet" href="{{ asset('css/material.grey-orange.min.css') }}">
    <style type="text/css">
        .demo-blog .on-the-road-again .mdl-card__media {
            background-image: url('{{ $detail->img_url }}');
        }

    </style>

    <script type="text/javascript">
        var map;
        var marker;
        var mygeocode = new google.maps.LatLng(13.730190, 100.779191);
        var geocoder = new google.maps.Geocoder();
        var infowindow = new google.maps.InfoWindow();
        function initialize() {
            var mapOptions = {
                zoom: 17,
                center: mygeocode,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
            marker = new google.maps.Marker({
                map: map,
                position: mygeocode,
                draggable: true
            });
            geocoder.geocode({'latLng': mygeocode}, function (results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    if (results[0]) {
                        $('#latitude').val(marker.getPosition().lat());
                        $('#longitude').val(marker.getPosition().lng());
                        infowindow.setContent(results[0].formatted_address);
                        infowindow.open(map, marker);
                    }
                }
            });
            google.maps.event.addListener(marker, 'dragend', function () {
                geocoder.geocode({'latLng': marker.getPosition()}, function (results, status) {
                    if (status == google.maps.GeocoderStatus.OK) {
                        if (results[0]) {
                            $('#latitude').val(marker.getPosition().lat());
                            $('#longitude').val(marker.getPosition().lng());
                            infowindow.setContent(results[0].formatted_address);
                            infowindow.open(map, marker);
                        }
                    }
                });
            });
        }
        google.maps.event.addDomListener(window, 'load', initialize);
    </script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>

    <style>
        #map {
            width: 100%;
            height: 400px;
        }
    </style>

</head>
<body>

<div class="demo-blog mdl-layout mdl-js-layout has-drawer is-upgraded">
    <main class="mdl-layout__content">
        <div class="demo-blog__posts mdl-grid">
            <img class="logo-kmitl" src="{{ asset('img/logo-web.png') }}">

            <div class="mdl-card on-the-road-again mdl-cell mdl-cell--12-col">
                <div class="mdl-card__media mdl-color-text--grey-50 min-size">
                    <h3>{{ $detail->name }}</h3>
                </div>
                <div class="mdl-color-text--grey-600 mdl-card__supporting-text">
                    {{ $detail->description }}
                </div>
                <div class="row">
                    <div class="col-xs-12 col-md-6 col-lg-4">
                        <div class="mdl-card__supporting-text meta mdl-color-text--grey-600">
                            <i class="fa fa-calendar fa-3x"></i>
                            <div>
                                <span>{{ $detail->start_date }} ถึง {{ $detail->end_date }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-6 col-lg-4">
                        <div class="mdl-card__supporting-text meta mdl-color-text--grey-600">
                            <i class="fa fa-clock-o fa-3x"></i>
                            <div>
                                <span>{{ $detail->start_time }} ถึง {{ $detail->end_time }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-6 col-lg-4">
                        <div class="mdl-card__supporting-text meta mdl-color-text--grey-600">
                            <i class="fa fa-money fa-3x"></i>
                            <div>
                                @if ($detail->cost != 0)
                                        {{ $detail->cost }} บาท
                                @else
                                        ฟรี!!!
                                @endif
                            </div>
                        </div>
                    </div>
                    <div id="map_canvas" style="width: 100%; height: 460px;"></div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-md-6 col-lg-4">
                        <div class="mdl-card__supporting-text meta mdl-color-text--grey-600">
                            <i class="fa fa-user fa-3x"></i>
                            <div>
                                <span>{{ $detail->contract->name }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-6 col-lg-4">
                        <div class="mdl-card__supporting-text meta mdl-color-text--grey-600">
                            <i class="fa fa-envelope fa-3x"></i>
                            <div>
                                <span><a href="mailto:{{ $detail->contract->email }}">{{ $detail->contract->email }}</a></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-6 col-lg-4">
                        <div class="mdl-card__supporting-text meta mdl-color-text--grey-600">
                            <i class="fa fa-phone-square fa-3x"></i>
                            <span>{{ $detail->contract->phone_number }}</span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-md-6 col-lg-4">
                        <div class="mdl-card__supporting-text meta mdl-color-text--grey-600">
                            <i class="fa fa-external-link fa-3x"></i>
                            <div>
                                <span>{{ $detail->contract->website }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-6 col-lg-4">
                        <div class="mdl-card__supporting-text meta mdl-color-text--grey-600">
                            <i class="fa fa-facebook fa-3x"></i>
                            <div>
                                <span><a href="{{ $detail->contract->facebook }}">{{ $detail->contract->facebook }}</a></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-6 col-lg-4">
                        <div class="mdl-card__supporting-text meta mdl-color-text--grey-600">
                            <i class="fa fa-twitter fa-3x"></i>
                            <span><a href="{{ $detail->contract->twitter }}">{{ $detail->contract->twitter }}</a></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <div class="mdl-layout__obfuscator"></div>
</div>
<!-- jQuery 2.2.3 -->
<script src="{{ asset('js/jquery-2.2.3.min.js') }}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
<!-- Material Design -->
<script src="{{ asset('js/material.min.js') }}"></script>
<script type="text/javascript">
    var mapOptions = {
        zoom: 16,
        center: new google.maps.LatLng(54.00, -3.00),
        mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    var geocoder = new google.maps.Geocoder();
    var address = '3410 Taft Blvd  Wichita Falls, TX 76308';
    geocoder.geocode( { 'address': address}, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
            map.setCenter(results[0].geometry.location);
            var marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location
            });
        } else {
            alert("Geocode was not successful for the following reason: " + status);
        }
    });
    var map = new google.maps.Map(document.getElementById("map"), mapOptions);
</script>
Raw

</body>
</html>